#!/bin/bash
echo " Пользователь: $USER "
echo "Директория: $(pwd)"
echo "Дата: $(date)"
echo "Кол-во файлов в дом директории: $(find ~ -maxdepth 1 -type f | wc -l)"

 Пользователь: knrzev 
Директория: /home/knrzev
Дата: Чт 14 мая 2026 11:24:10 MSK
Кол-во файлов в дом директории: 9
